<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>ec7cade9-a679-4c5f-b007-53b637b4a797</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>

		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />

		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />

		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.12">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />

		<PackageReference Include="Resend" Version="0.19.0" />

	</ItemGroup>

	<ItemGroup>

		<Compile Remove="App.xaml.cs" />
		<Compile Remove="TraditionsPage.xaml.cs" />
		<Compile Remove="UI\**\*.cs" />
		<Compile Remove="DataTraditions\**\*.cs" />
		<Compile Remove="LocalData\**\*.cs" />
		<Compile Remove="Logic\**\*.cs" />
		<Compile Remove="MigrationsLocal\**\*.cs" />

		<Compile Remove="Migrations\20260806171021_AddImagePathToTraditions.cs" />
		<Compile Remove="Migrations\20260806171021_AddImagePathToTraditions.Designer.cs" />
		<Compile Remove="Migrations\TravelBookDbContextModelSnapshot.cs" />

		<ApplicationDefinition Remove="App.xaml" />
		<Page Remove="**\*.xaml" />

	</ItemGroup>

</Project>